" For the most part, settings were 'borrowed' from yadr.
" Use Vim settings, rather than Vi settings.
" The must be first, because it changes other options as a side effect.
set nocompatible

" ================= General Config ==================
set number                      " Display line numbers
set backspace=indent,eol,start	" Allow backspace in insert mode
set history=1000		" Store 1000 lines of :cmdline history
set showcmd			    " Show incomplete cmds at the bottom
set showmode			" Show current mode at the bottom
set visualbell			" No sounds
set autoread			" Reload files changed outside vim
set hidden              " Buffers exist in the background

" Turn on syntax highlighting
syntax on

" Allow the mouse to move the pointer
set mouse=a

" =============== Vundle Initialization =============
" This loads all the plugins specified in ~/.vim/vundles.vim
" Use Vundle plugin to manage all other plugins
if filereadable(expand("~/.vim/vundles.vim"))
	source ~/.vim/vundles.vim
endif

" Turn off swap files
set noswapfile
set nobackup
set nowb

" =============== Persistent Undo ===================
" Keep undo history across sessions, by storing in file.
if has('persistent_undo') && !isdirectory(expand('~').'/.vim/backups')
	silent !mkdir ~/.vim/backups > /dev/null 2>&1
	set undodir=~/.vim/backups
	set undofile
endif

" =============== Indentation =======================
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
" Toggle between 2 and 4 space tabs with \4 and \2
nmap <leader>4 :set tabstop=4 shiftwidth=4 softtabstop=4<CR>
nmap <leader>2 :set tabstop=2 shiftwidth=2 softtabstop=2<CR>

" Auto indent pasted text
nnoremap p p=`]<C-o>
nnoremap P P=`]<C-o>

filetype plugin on
filetype indent on

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

set nowrap	    " Don't wrap lines
set linebreak	" But wrap lines at convenient points

" =============== Folds =============================
set foldmethod=indent	" Fold based on indent
set foldnestmax=3	    " Deepest fold is 3 levels
set nofoldenable	    " Don't fold by default

" =============== Completion ========================
set wildmode=list:longest
set wildmenu			    " <C-n> and <C-p> to scroll through matches
set wildignore=*.o,*.obj,*~	" Stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*DS_Store*
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

" =============== Scrolling =========================
set scrolloff=8		" Start scrolling 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" =============== Search ============================
set incsearch	" Find the next match as we type the search
set hlsearch	" Highlight searches by default
set ignorecase	" Ignore case when searching...
set smartcase	" ...unless we type a capital

" =============== Terminal ==========================
set t_Co=256 " Allow 256 colours
" Override line number colors to be grey
hi LineNr ctermfg=20
hi CursorLineNr ctermfg=20
" Override statements and keywords to be red
" hi Statement ctermfg=1
" Make special comments blue and italic
hi SpecialComment term=bold cterm=italic ctermfg=4 guifg=SlateBlue
hi! link Comment SpecialComment

" =============== Custom Settings ===================
so ~/.vim/settings.vim
